"""modelo inicial

Revision ID: 29af79608fa7
Revises: 
Create Date: 2026-07-17 16:46:12.739386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29af79608fa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_uaslp', sa.String(length=10), nullable=False),
    sa.Column('cve_larga', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumno_cve_uaslp'), 'alumno', ['cve_uaslp'], unique=True)
    op.create_table('carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrera_clave'), 'carrera', ['clave'], unique=True)
    op.create_table('ciclo_escolar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('anio_inicio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=4), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciclo_escolar_nombre'), 'ciclo_escolar', ['nombre'], unique=True)
    op.create_index(op.f('ix_ciclo_escolar_orden'), 'ciclo_escolar', ['orden'], unique=False)
    op.create_table('codigo_calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('resultado', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigo_calificacion_clave'), 'codigo_calificacion', ['clave'], unique=True)
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filas_totales', sa.Integer(), nullable=False),
    sa.Column('filas_insertadas', sa.Integer(), nullable=False),
    sa.Column('filas_actualizadas', sa.Integer(), nullable=False),
    sa.Column('filas_rechazadas', sa.Integer(), nullable=False),
    sa.Column('errores', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_materia', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materia_cve_materia'), 'materia', ['cve_materia'], unique=True)
    op.create_table('modalidad_titulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalidad_titulacion_clave'), 'modalidad_titulacion', ['clave'], unique=True)
    op.create_table('situacion_academica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('es_desercion', sa.Boolean(), nullable=False),
    sa.Column('es_egreso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situacion_academica_clave'), 'situacion_academica', ['clave'], unique=True)
    op.create_table('tipo_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('es_ordinario', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_examen_clave'), 'tipo_examen', ['clave'], unique=True)
    op.create_table('plan_estudios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrera_id', 'nombre', name='uq_plan_carrera_nombre')
    )
    op.create_table('plan_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('caracter', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_estudios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'materia_id', name='uq_plan_materia')
    )
    op.create_table('trayectoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('cohorte', sa.Integer(), nullable=False),
    sa.Column('situacion_id', sa.Integer(), nullable=True),
    sa.Column('tutor', sa.String(length=200), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('fecha_pasante', sa.Date(), nullable=True),
    sa.Column('fecha_titulacion', sa.Date(), nullable=True),
    sa.Column('opcion_titulacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], ),
    sa.ForeignKeyConstraint(['opcion_titulacion_id'], ['modalidad_titulacion.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_estudios.id'], ),
    sa.ForeignKeyConstraint(['situacion_id'], ['situacion_academica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'carrera_id', name='uq_trayectoria_alumno_carrera')
    )
    op.create_index(op.f('ix_trayectoria_cohorte'), 'trayectoria', ['cohorte'], unique=False)
    op.create_table('registro_kardex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trayectoria_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_examen_id', sa.Integer(), nullable=True),
    sa.Column('calificacion_numerica', sa.Integer(), nullable=True),
    sa.Column('codigo_calificacion_id', sa.Integer(), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('fecha_cal', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclo_escolar.id'], ),
    sa.ForeignKeyConstraint(['codigo_calificacion_id'], ['codigo_calificacion.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['tipo_examen_id'], ['tipo_examen.id'], ),
    sa.ForeignKeyConstraint(['trayectoria_id'], ['trayectoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_kardex_ciclo_id'), 'registro_kardex', ['ciclo_id'], unique=False)
    op.create_index(op.f('ix_registro_kardex_materia_id'), 'registro_kardex', ['materia_id'], unique=False)
    op.create_index(op.f('ix_registro_kardex_trayectoria_id'), 'registro_kardex', ['trayectoria_id'], unique=False)
    op.create_table('titulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trayectoria_id', sa.Integer(), nullable=False),
    sa.Column('modalidad_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['modalidad_id'], ['modalidad_titulacion.id'], ),
    sa.ForeignKeyConstraint(['trayectoria_id'], ['trayectoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trayectoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titulacion')
    op.drop_index(op.f('ix_registro_kardex_trayectoria_id'), table_name='registro_kardex')
    op.drop_index(op.f('ix_registro_kardex_materia_id'), table_name='registro_kardex')
    op.drop_index(op.f('ix_registro_kardex_ciclo_id'), table_name='registro_kardex')
    op.drop_table('registro_kardex')
    op.drop_index(op.f('ix_trayectoria_cohorte'), table_name='trayectoria')
    op.drop_table('trayectoria')
    op.drop_table('plan_materia')
    op.drop_table('plan_estudios')
    op.drop_index(op.f('ix_tipo_examen_clave'), table_name='tipo_examen')
    op.drop_table('tipo_examen')
    op.drop_index(op.f('ix_situacion_academica_clave'), table_name='situacion_academica')
    op.drop_table('situacion_academica')
    op.drop_index(op.f('ix_modalidad_titulacion_clave'), table_name='modalidad_titulacion')
    op.drop_table('modalidad_titulacion')
    op.drop_index(op.f('ix_materia_cve_materia'), table_name='materia')
    op.drop_table('materia')
    op.drop_table('import_log')
    op.drop_index(op.f('ix_codigo_calificacion_clave'), table_name='codigo_calificacion')
    op.drop_table('codigo_calificacion')
    op.drop_index(op.f('ix_ciclo_escolar_orden'), table_name='ciclo_escolar')
    op.drop_index(op.f('ix_ciclo_escolar_nombre'), table_name='ciclo_escolar')
    op.drop_table('ciclo_escolar')
    op.drop_index(op.f('ix_carrera_clave'), table_name='carrera')
    op.drop_table('carrera')
    op.drop_index(op.f('ix_alumno_cve_uaslp'), table_name='alumno')
    op.drop_table('alumno')
    # ### end Alembic commands ###
